### ISSUE TITLE
Link to documentation not working / Documentation deployed to different URL

### ISSUE THREAD

**Issue by mipals** [oxfordcontrol/ClarabelDocs#18]
Was the name of this repository recently changed? The documentation seems to now be deployed on 

[https://oxfordcontrol.github.io/clarabel](https://oxfordcontrol.github.io/clarabel)

previously the documentation was deployed on

[https://oxfordcontrol.github.io/ClarabelDocs/](https://oxfordcontrol.github.io/ClarabelDocs/)

As a result of the change many links to the documentation are currently linking to nowhere.

**Comment by goulart-paul** [comment]
Yes, I renamed the documentation repo thinking that the new name looked like a more obvious generic main page for the solver.    I assumed that links would redirect since that's what happens with git repo links.   

Which links are broken?   If they are internal links on the documentation then it's fixable, but if there are a bunch of external links to it (are there?) then probably best to just change the name back.

Sorry for any confusion.

**Comment by mipals** [comment]
I don't know of any external links. 

Yes, the Julia and Rust repo links are broken. In addition to that, the link in this repo is also broken.

**Comment by goulart-paul** [comment]
I just changed it back, because I realised that links on the cvxpy support pages are also broken now.
