### ISSUE TITLE
Undocumented solver output

### ISSUE THREAD

**Issue by lequant40** [oxfordcontrol/ClarabelDocs#6]
Hello there,

It seems the documentation on possible solver output is missing a couple of fields, c.f. https://github.com/oxfordcontrol/Clarabel.rs/blob/abff1b457871c2e8a92a6504749321117e263e35/src/python/impl_default_py.rs#L96-L102

_AlmostSolved,
AlmostPrimalInfeasible,
AlmostDualInfeasible,
NumericalError,
InsufficientProgress,_

I am not sure as to what they mean exactly, so, would it be possible to document them for your users?

Cheers,

Roman

**Comment by goulart-paul** [comment]
Apologies.   Yes, we can add some clarification to the docs in the next release (which should come very soon).

In summary: 

The solver has two conditions that will cause it to halt before reaching convergence or hitting time/iteration limits:

: `InsufficientProgress` means that the solver is either stalled or the solution quality has started to regress. 

: `NumericalError` is sort of a catch-all error.    It typically (maybe even always, would need to check) means that the solver has tried and failed to factor a linear system to compute an interior point step.   This is generally due to the appearance of bad pivot or other numerical conditioning problems at high accuracy.

The other three status you mention are the same as the non-"almost" variants, but they are just evaluated against the reduced accuracy settings as described here: https://oxfordcontrol.github.io/ClarabelDocs/stable/api_settings/

We would report `Solved` if the solver reaches the accuracy specified by the parameters `tol_gap_abs`, `tol_gap_rel` and `tol_feas`.   If it hits its iteration/time limit without converging to within those limits, or otherwise encounters a problem (see above...), we would then a final check against `reduced_tol_gap_abs` etc.    If the solution satisfies those more relaxed bounds, we would report `AlmostSolved` instead or the error or iteration limit condition.   It is a similar story for `AlmostPrimalInfeasible` and `AlmostDualInfeasible`.

In particular, note that `AlmostPrimalInfeasible` doesn't mean "the problem is nearly, but not quite, infeasible".   It means "we have a certificate of infeasibility, but it only satisfies reduced tolerances".

**Comment by lequant40** [comment]
Ah, thanks a lot for the explanations, and especially, about the 'almost', indeed, I was wondering.

Now back to testing Clarabel :-) !

**Comment by lequant40** [comment]
Thanks a lot !
